# Generated by Django 4.2.2 on 2023-06-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataScience', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PythonClassModel',
            new_name='ComputerScienceModel',
        ),
    ]
